services:
  laundrydormapi:
    image: ${DOCKER_REGISTRY-}laundrydormapi
    build:
      context: .
      dockerfile: LaundryDormApi/Dockerfile #Dockerfile path for the backend. Where its located in asp.net. This is adjusted after context (line above)
      # Rememeber, its the docker yaml (build) that sits at the very root and extract all the info from each dockerfiles to build upon them.

    #volumes:
    #  - ./LaundryDormApi:/app
    #  - ~/.aspnet/https:/root/.aspnet/https:ro
    #working_dir: /app
    #command: dotnet watch run

    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DbContextConnection=Server=mariadb;Database=LaundryDormBase;User=root;Password=Testingtesting1234
      - ConnectionStrings__AuthContextConnection=Server=mariadb;Database=LaundryDormAuthDb;User=root;Password=Testingtesting1234
    depends_on:
      - mariadb


  laundrydormfrontend:
    build: 
      context: ./LaundryDormReact/laundrydorm_vite
      dockerfile: Dockerfile #Looking for/at the dockerfile at the context (frontend context) path level. Need one dockerfile for the frontend
      target: builder
    volumes:
      - ./LaundryDormReact/laundrydorm_vite:/app
      - /app/node_modules #Need this to prevent overwriting node_modules
    working_dir: /app
    command: npm run dev #To run the website upon build
    ports:
     - "3000:5173"
    depends_on:
      - laundrydormapi

  mariadb:
    image: mariadb:latest 
    #For mariadb, we are not relying on dockerfile, but for the image. 
    # This is because mariadb docker image already handles setups (starting DB server, creating user/datavase for environment variable, exposing port etc)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Testingtesting1234
      MYSQL_DATABASE: LaundryDormBase
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mariadb_data:
   


     


